name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

# jobs:
#   unit_tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Checkout source code"
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 1
